### ISSUE TITLE
example doesn't validate

### ISSUE THREAD

**Issue by nsheff** [databio/bed_maker#12]
not sure if this is a problem with bedmaker or eido...

```
eido -p example/cfg.yaml -s pep_schema.yaml 
Reading sample annotations sheet: '/home/nsheff/code/bedmaker/example/samples_to_convert.csv'
Storing sample table from file '/home/nsheff/code/bedmaker/example/samples_to_convert.csv'
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/eido", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.7/site-packages/eido/eido.py", line 199, in main
    validate_project(p, args.schema, args.exclude_case)
  File "/home/nsheff/.local/lib/python3.7/site-packages/eido/eido.py", line 128, in validate_project
    _validate_object(project_dict, _preprocess_schema(schema_dict), exclude_case)
  File "/home/nsheff/.local/lib/python3.7/site-packages/eido/eido.py", line 113, in _validate_object
    raise e
  File "/home/nsheff/.local/lib/python3.7/site-packages/eido/eido.py", line 110, in _validate_object
    jsonschema.validate(object, schema)
  File "/home/nsheff/.local/lib/python3.7/site-packages/jsonschema/validators.py", line 899, in validate
    raise error
jsonschema.exceptions.ValidationError: 'TRUE' is not of type 'boolean'

Failed validating 'type' in schema['properties']['_samples']['items']['properties']['narrowpeak']:
    {'description': 'whether the regions are narrow (transcription factor '
                    'implies narrow, histone mark implies broad peaks)',
     'type': 'boolean'}

On instance['_samples'][0]['narrowpeak']:
    'TRUE'

```

**Comment by joseverdezoto** [comment]
@nsheff when I wrote/tested the pipeline, I created the test .csv file in excel, which defined booleans as `TRUE` or `FALSE`. Could it be that `eido` doesn't recognize that boolean format?

**Comment by nsheff** [comment]
pandas reads all that stuff in as text, so I think it's a string "TRUE" rather than `True`.

@stolarczyk , due to the way peppy is loading these sheets, I don't think we can set a value as a boolean in one of these schemas, can we?

**Comment by nsheff** [comment]
@joseverdezoto 

just FYI you have another error here after eliminating the boolean requirement in the schema: 

```
eido -p example/cfg.yaml -s ../schema.databio.org/bed_maker.yaml 
Reading sample annotations sheet: '/home/nsheff/code/bedmaker/example/samples_to_convert.csv'
Storing sample table from file '/home/nsheff/code/bedmaker/example/samples_to_convert.csv'
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/eido", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.7/site-packages/eido/eido.py", line 192, in main
    validate_project(p, args.schema, args.exclude_case)
  File "/home/nsheff/.local/lib/python3.7/site-packages/eido/eido.py", line 121, in validate_project
    _validate_object(project_dict, _preprocess_schema(schema_dict), exclude_case)
  File "/home/nsheff/.local/lib/python3.7/site-packages/eido/eido.py", line 106, in _validate_object
    raise e
  File "/home/nsheff/.local/lib/python3.7/site-packages/eido/eido.py", line 103, in _validate_object
    jsonschema.validate(object, schema)
  File "/home/nsheff/.local/lib/python3.7/site-packages/jsonschema/validators.py", line 899, in validate
    raise error
jsonschema.exceptions.ValidationError: 'bigWig ' is not one of ['bigWig', 'bigBed', 'bed', 'wig', 'bedGraph']

Failed validating 'enum' in schema['properties']['_samples']['items']['properties']['format']:
    {'description': 'file format',
     'enum': ['bigWig', 'bigBed', 'bed', 'wig', 'bedGraph'],
     'type': 'string'}

On instance['_samples'][2]['format']:
    'bigWig '
```
see the space after 'bigWig'? be careful with whitespace.

after fixing these errors I get:

```
eido -p example/cfg.yaml -s ../schema.databio.org/bed_maker.yaml 
Reading sample annotations sheet: '/home/nsheff/code/bedmaker/example/samples_to_convert.csv'
Storing sample table from file '/home/nsheff/code/bedmaker/example/samples_to_convert.csv'
Validation successful
```

**Comment by stolarczyk** [comment]
> so I think it's a string "TRUE" rather than True 

yes, that's how I've been using this

**Comment by nsheff** [comment]
?
