### ISSUE TITLE
Error while using bedmaker through command line (dev branch)

### ISSUE THREAD

**Issue by khoroshevskyi** [databio/bed_maker#20]
I have refactored code and added const, test, github actions and setup files.
Python API works good, but when trying run bedmaker through command line tool there is an error:
```
bnt4me@cphg-Precision-5560:~/Virginia/repos/bedmaker$ bedmaker
Traceback (most recent call last):
  File "/home/bnt4me/.local/bin/bedmaker", line 5, in <module>
    from bedmaker.bedmaker import main
  File "/home/bnt4me/.local/lib/python3.10/site-packages/bedmaker/__init__.py", line 2, in <module>
    from .bedmaker import *
  File "/home/bnt4me/.local/lib/python3.10/site-packages/bedmaker/bedmaker.py", line 4, in <module>
    import pypiper
  File "/home/bnt4me/.local/lib/python3.10/site-packages/pypiper/__init__.py", line 2, in <module>
    from .manager import *
  File "/home/bnt4me/.local/lib/python3.10/site-packages/pypiper/manager.py", line 17, in <module>
    import psutil
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 95, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/lib/python3/dist-packages/psutil/__init__.py)
```
It can be caused by [pypiper](https://github.com/databio/pypiper)
Help needed!

**Comment by nsheff** [comment]
It works for me. So, it's local to your computer.
